# Generated by Django 3.0 on 2021-06-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200324_2334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='College',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='college',
        ),
    ]
