# Generated by Django 3.0 on 2021-06-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210623_0021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='College',
            new_name='Movie',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='college',
            new_name='movie',
        ),
    ]
