# Generated by Django 3.2.6 on 2021-08-26 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'ENQUIRY DATA'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'IMAGES'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name_plural': 'COLLEGE'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'COLLEGE_REVIEW'},
        ),
    ]
