# Generated by Django 3.0 on 2021-08-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210828_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=500)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
